### PR TITLE
added closing parentheses and capitalized first word of sentence

### PR DESCRIPTION
**Pull request by zacharyburnett**
added closing parentheses and capitalized first word of sentence

### CODE REVIEW

**Comment by zacharyburnett** [comment]
is it possible to add an auto-build of the document with something like GitHub Actions?

**Comment by zacharyburnett** [comment]
> is it possible to add an auto-build of the document with something like GitHub Actions?

i went ahead and made a pull request for this #2

**Comment by zacharyburnett** [comment]
rebased onto #2 to use the build workflow

**Comment by ChainlessCoder** [comment]
Great idea, Zach!

**Pull request merged**
